// Generated by Wrangler by running `wrangler types`

interface Env {
	URLS: KVNamespace;
	PASSWORD: string;
	PASSWORD_REQUIRE: boolean;
	HOST_WHITELIST: string[];
	KEY_MIN_LENGTH: number;
	KEY_REMOVE: boolean;
}